[target.x86_64-unknown-linux-gnu]
# "sink-common=false" tells LLVM: "Don't try to merge common code in huge switch statements."
# This prevents the O(N^2) behavior in SimplifyCFG.
rustflags = ["-C", "llvm-args=-simplifycfg-sink-common=false"]
